//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Application.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.Visits = new HashSet<Visits>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CircleID { get; set; }
        public string Cabinet { get; set; }
        public string WeekDay { get; set; }
        public string StartTime { get; set; }
        public string FinishTime { get; set; }
        public int HalfYear { get; set; }
        public string AcademicYear { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual Circles Circles { get; set; }
        public virtual Class Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Visits> Visits { get; set; }
    }
}
